fs=require('fs')
sys=require('sys')
files=[
  './json2.js'
 ,'./score.js'
 ,'./words_classic_texts.js'
 ,'./words_database.js'
 ,'./display.js'
 ,'./menu_display.js'
 ,'./level_display.js'
 ,'./score_display.js'
 ,'./menu.js'
 ,'./keys.js'
 ,'./level.js'
 ,'./store.js'
 ,'./typer.js'
 ,'./js.js'
]
len=files.length
out=''
for(i=0;i<len;i++)
  out+=fs.readFileSync(files[i])
sys.puts(out)
